# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(493, 588)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../PycharmProjects/PyQtTutorial/ALUMIE/Design/images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setAutoFillBackground(False)
        Settings.setStyleSheet("background-color:white\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -439, 450, 948))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.ChargeHumidity1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.ChargeHumidity1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.ChargeHumidity1.setProperty("value", 35.0)
        self.ChargeHumidity1.setObjectName("ChargeHumidity1")
        self.verticalLayout_12.addWidget(self.ChargeHumidity1)
        self.HumidityWhiteMud1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.HumidityWhiteMud1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.HumidityWhiteMud1.setProperty("value", 34.0)
        self.HumidityWhiteMud1.setObjectName("HumidityWhiteMud1")
        self.verticalLayout_12.addWidget(self.HumidityWhiteMud1)
        self.HumidityAluminumHydroxide1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.HumidityAluminumHydroxide1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.HumidityAluminumHydroxide1.setProperty("value", 10.4)
        self.HumidityAluminumHydroxide1.setObjectName("HumidityAluminumHydroxide1")
        self.verticalLayout_12.addWidget(self.HumidityAluminumHydroxide1)
        self.HumidityDumpMud1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.HumidityDumpMud1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.HumidityDumpMud1.setProperty("value", 33.0)
        self.HumidityDumpMud1.setObjectName("HumidityDumpMud1")
        self.verticalLayout_12.addWidget(self.HumidityDumpMud1)
        self.gridLayout.addLayout(self.verticalLayout_12, 0, 2, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.gridLayout.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setContentsMargins(9, -1, -1, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DumpMud1 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.DumpMud1.setMinimumSize(QtCore.QSize(0, 3))
        self.DumpMud1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.DumpMud1.setDecimals(3)
        self.DumpMud1.setProperty("value", 6.938)
        self.DumpMud1.setObjectName("DumpMud1")
        self.verticalLayout_6.addWidget(self.DumpMud1)
        self.WhiteMud1 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.WhiteMud1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.WhiteMud1.setProperty("value", 0.06)
        self.WhiteMud1.setObjectName("WhiteMud1")
        self.verticalLayout_6.addWidget(self.WhiteMud1)
        self.CarbonMud1 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.CarbonMud1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CarbonMud1.setDecimals(4)
        self.CarbonMud1.setProperty("value", 0.0398)
        self.CarbonMud1.setObjectName("CarbonMud1")
        self.verticalLayout_6.addWidget(self.CarbonMud1)
        self.AluminumHydroxide1 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.AluminumHydroxide1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.AluminumHydroxide1.setProperty("value", 0.8)
        self.AluminumHydroxide1.setObjectName("AluminumHydroxide1")
        self.verticalLayout_6.addWidget(self.AluminumHydroxide1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777204, 16777204))
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_50 = QtWidgets.QLabel(self.groupBox_9)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_15.addWidget(self.label_50)
        self.Release1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.Release1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Release1.setProperty("value", 84.6)
        self.Release1.setObjectName("Release1")
        self.horizontalLayout_15.addWidget(self.Release1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_51 = QtWidgets.QLabel(self.groupBox_9)
        self.label_51.setWordWrap(False)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_16.addWidget(self.label_51)
        self.Extract1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.Extract1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Extract1.setProperty("value", 87.1)
        self.Extract1.setObjectName("Extract1")
        self.horizontalLayout_16.addWidget(self.Extract1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_52 = QtWidgets.QLabel(self.groupBox_9)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_17.addWidget(self.label_52)
        self.Mass1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.Mass1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Mass1.setMaximum(1000.0)
        self.Mass1.setProperty("value", 1000.0)
        self.Mass1.setObjectName("Mass1")
        self.horizontalLayout_17.addWidget(self.Mass1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_8 = QtWidgets.QLabel(self.groupBox_9)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_18.addWidget(self.label_8)
        self.SiliconModuleDo1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.SiliconModuleDo1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.SiliconModuleDo1.setProperty("value", 30.0)
        self.SiliconModuleDo1.setObjectName("SiliconModuleDo1")
        self.horizontalLayout_18.addWidget(self.SiliconModuleDo1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_53 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_19.addWidget(self.label_53)
        self.SiliconModulePosle1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.SiliconModulePosle1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.SiliconModulePosle1.setMaximum(1000.0)
        self.SiliconModulePosle1.setProperty("value", 400.0)
        self.SiliconModulePosle1.setObjectName("SiliconModulePosle1")
        self.horizontalLayout_19.addWidget(self.SiliconModulePosle1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_9 = QtWidgets.QLabel(self.groupBox_9)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_20.addWidget(self.label_9)
        self.CMAlum1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.CMAlum1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CMAlum1.setProperty("value", 1.5)
        self.CMAlum1.setObjectName("CMAlum1")
        self.horizontalLayout_20.addWidget(self.CMAlum1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_54 = QtWidgets.QLabel(self.groupBox_9)
        self.label_54.setWordWrap(True)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_21.addWidget(self.label_54)
        self.CMCarbon1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.CMCarbon1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CMCarbon1.setProperty("value", 2.0)
        self.CMCarbon1.setObjectName("CMCarbon1")
        self.horizontalLayout_21.addWidget(self.CMCarbon1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_55 = QtWidgets.QLabel(self.groupBox_9)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_22.addWidget(self.label_55)
        self.CMRegen1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.CMRegen1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CMRegen1.setProperty("value", 3.4)
        self.CMRegen1.setObjectName("CMRegen1")
        self.horizontalLayout_22.addWidget(self.CMRegen1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_23.addWidget(self.label_12)
        self.CMOAlum1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.CMOAlum1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CMOAlum1.setProperty("value", 2.7)
        self.CMOAlum1.setObjectName("CMOAlum1")
        self.horizontalLayout_23.addWidget(self.CMOAlum1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_23)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 286))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setLineWidth(1)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_3.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_3.addWidget(self.label_25)
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_3.addWidget(self.label_27)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Crushing1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.Crushing1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Crushing1.setProperty("value", 0.3)
        self.Crushing1.setObjectName("Crushing1")
        self.verticalLayout_4.addWidget(self.Crushing1)
        self.Grind1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.Grind1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Grind1.setProperty("value", 0.3)
        self.Grind1.setObjectName("Grind1")
        self.verticalLayout_4.addWidget(self.Grind1)
        self.Baking1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.Baking1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Baking1.setProperty("value", 0.3)
        self.Baking1.setObjectName("Baking1")
        self.verticalLayout_4.addWidget(self.Baking1)
        self.BakCrushing1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.BakCrushing1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.BakCrushing1.setProperty("value", 0.2)
        self.BakCrushing1.setObjectName("BakCrushing1")
        self.verticalLayout_4.addWidget(self.BakCrushing1)
        self.ChemicalLosses1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.ChemicalLosses1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.ChemicalLosses1.setProperty("value", 12.9)
        self.ChemicalLosses1.setObjectName("ChemicalLosses1")
        self.verticalLayout_4.addWidget(self.ChemicalLosses1)
        self.Underwashing1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.Underwashing1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Underwashing1.setProperty("value", 0.5)
        self.Underwashing1.setObjectName("Underwashing1")
        self.verticalLayout_4.addWidget(self.Underwashing1)
        self.Desilting1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.Desilting1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Desilting1.setProperty("value", 0.1)
        self.Desilting1.setObjectName("Desilting1")
        self.verticalLayout_4.addWidget(self.Desilting1)
        self.Carbonation1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.Carbonation1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Carbonation1.setProperty("value", 0.2)
        self.Carbonation1.setObjectName("Carbonation1")
        self.verticalLayout_4.addWidget(self.Carbonation1)
        self.Calcination1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.Calcination1.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Calcination1.setProperty("value", 0.6)
        self.Calcination1.setObjectName("Calcination1")
        self.verticalLayout_4.addWidget(self.Calcination1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -439, 450, 948))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.ChargeHumidity2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.ChargeHumidity2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.ChargeHumidity2.setProperty("value", 35.0)
        self.ChargeHumidity2.setObjectName("ChargeHumidity2")
        self.verticalLayout_13.addWidget(self.ChargeHumidity2)
        self.HumidityWhiteMud2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.HumidityWhiteMud2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.HumidityWhiteMud2.setProperty("value", 34.0)
        self.HumidityWhiteMud2.setObjectName("HumidityWhiteMud2")
        self.verticalLayout_13.addWidget(self.HumidityWhiteMud2)
        self.HumidityAluminumHydroxide2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.HumidityAluminumHydroxide2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.HumidityAluminumHydroxide2.setProperty("value", 10.4)
        self.HumidityAluminumHydroxide2.setObjectName("HumidityAluminumHydroxide2")
        self.verticalLayout_13.addWidget(self.HumidityAluminumHydroxide2)
        self.HumidityDumpMud2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.HumidityDumpMud2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.HumidityDumpMud2.setProperty("value", 33.0)
        self.HumidityDumpMud2.setObjectName("HumidityDumpMud2")
        self.verticalLayout_13.addWidget(self.HumidityDumpMud2)
        self.gridLayout_3.addLayout(self.verticalLayout_13, 0, 2, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_14.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_14.addWidget(self.label_29)
        self.gridLayout_3.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setContentsMargins(9, -1, -1, 9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_30 = QtWidgets.QLabel(self.groupBox_6)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_10.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.groupBox_6)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_10.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.groupBox_6)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_10.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_10.addWidget(self.label_33)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.DumpMud2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.DumpMud2.setMinimumSize(QtCore.QSize(0, 3))
        self.DumpMud2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.DumpMud2.setDecimals(3)
        self.DumpMud2.setProperty("value", 6.938)
        self.DumpMud2.setObjectName("DumpMud2")
        self.verticalLayout_15.addWidget(self.DumpMud2)
        self.WhiteMud2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.WhiteMud2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.WhiteMud2.setProperty("value", 0.06)
        self.WhiteMud2.setObjectName("WhiteMud2")
        self.verticalLayout_15.addWidget(self.WhiteMud2)
        self.CarbonMud2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.CarbonMud2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CarbonMud2.setDecimals(4)
        self.CarbonMud2.setProperty("value", 0.0398)
        self.CarbonMud2.setObjectName("CarbonMud2")
        self.verticalLayout_15.addWidget(self.CarbonMud2)
        self.AluminumHydroxide2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.AluminumHydroxide2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.AluminumHydroxide2.setProperty("value", 0.8)
        self.AluminumHydroxide2.setObjectName("AluminumHydroxide2")
        self.verticalLayout_15.addWidget(self.AluminumHydroxide2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_15)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777204, 16777204))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_34 = QtWidgets.QLabel(self.groupBox_7)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_6.addWidget(self.label_34)
        self.Release2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.Release2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Release2.setProperty("value", 84.6)
        self.Release2.setObjectName("Release2")
        self.horizontalLayout_6.addWidget(self.Release2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_35 = QtWidgets.QLabel(self.groupBox_7)
        self.label_35.setWordWrap(False)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_7.addWidget(self.label_35)
        self.Extract2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.Extract2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Extract2.setProperty("value", 87.1)
        self.Extract2.setObjectName("Extract2")
        self.horizontalLayout_7.addWidget(self.Extract2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_36 = QtWidgets.QLabel(self.groupBox_7)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_8.addWidget(self.label_36)
        self.Mass2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.Mass2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Mass2.setMaximum(1000.0)
        self.Mass2.setProperty("value", 1000.0)
        self.Mass2.setObjectName("Mass2")
        self.horizontalLayout_8.addWidget(self.Mass2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.SiliconModuleDo2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.SiliconModuleDo2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.SiliconModuleDo2.setProperty("value", 30.0)
        self.SiliconModuleDo2.setObjectName("SiliconModuleDo2")
        self.horizontalLayout_9.addWidget(self.SiliconModuleDo2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_47 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setWordWrap(True)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_10.addWidget(self.label_47)
        self.SiliconModulePosle2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.SiliconModulePosle2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.SiliconModulePosle2.setMaximum(1000.0)
        self.SiliconModulePosle2.setProperty("value", 400.0)
        self.SiliconModulePosle2.setObjectName("SiliconModulePosle2")
        self.horizontalLayout_10.addWidget(self.SiliconModulePosle2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.CMAlum2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.CMAlum2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CMAlum2.setProperty("value", 1.5)
        self.CMAlum2.setObjectName("CMAlum2")
        self.horizontalLayout_11.addWidget(self.CMAlum2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_48 = QtWidgets.QLabel(self.groupBox_7)
        self.label_48.setWordWrap(True)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_13.addWidget(self.label_48)
        self.CMCarbon2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.CMCarbon2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CMCarbon2.setProperty("value", 2.0)
        self.CMCarbon2.setObjectName("CMCarbon2")
        self.horizontalLayout_13.addWidget(self.CMCarbon2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_49 = QtWidgets.QLabel(self.groupBox_7)
        self.label_49.setWordWrap(True)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_14.addWidget(self.label_49)
        self.CMRegen2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.CMRegen2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CMRegen2.setProperty("value", 3.4)
        self.CMRegen2.setObjectName("CMRegen2")
        self.horizontalLayout_14.addWidget(self.CMRegen2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.CMOAlum2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.CMOAlum2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.CMOAlum2.setProperty("value", 2.7)
        self.CMOAlum2.setObjectName("CMOAlum2")
        self.horizontalLayout_12.addWidget(self.CMOAlum2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 286))
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_37 = QtWidgets.QLabel(self.groupBox_8)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_18.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.groupBox_8)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_18.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.groupBox_8)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_18.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.groupBox_8)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_18.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.groupBox_8)
        self.label_41.setLineWidth(1)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_18.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.groupBox_8)
        self.label_42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_18.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.groupBox_8)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_18.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.groupBox_8)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_18.addWidget(self.label_44)
        self.label_46 = QtWidgets.QLabel(self.groupBox_8)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_18.addWidget(self.label_46)
        self.horizontalLayout_4.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Crushing2 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.Crushing2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Crushing2.setProperty("value", 0.3)
        self.Crushing2.setObjectName("Crushing2")
        self.verticalLayout_19.addWidget(self.Crushing2)
        self.Grind2 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.Grind2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Grind2.setProperty("value", 0.3)
        self.Grind2.setObjectName("Grind2")
        self.verticalLayout_19.addWidget(self.Grind2)
        self.Baking2 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.Baking2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Baking2.setProperty("value", 0.3)
        self.Baking2.setObjectName("Baking2")
        self.verticalLayout_19.addWidget(self.Baking2)
        self.BakCrushing2 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.BakCrushing2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.BakCrushing2.setProperty("value", 0.2)
        self.BakCrushing2.setObjectName("BakCrushing2")
        self.verticalLayout_19.addWidget(self.BakCrushing2)
        self.ChemicalLosses2 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.ChemicalLosses2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.ChemicalLosses2.setProperty("value", 12.9)
        self.ChemicalLosses2.setObjectName("ChemicalLosses2")
        self.verticalLayout_19.addWidget(self.ChemicalLosses2)
        self.Underwashing2 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.Underwashing2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Underwashing2.setProperty("value", 0.5)
        self.Underwashing2.setObjectName("Underwashing2")
        self.verticalLayout_19.addWidget(self.Underwashing2)
        self.Desilting2 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.Desilting2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Desilting2.setProperty("value", 0.1)
        self.Desilting2.setObjectName("Desilting2")
        self.verticalLayout_19.addWidget(self.Desilting2)
        self.Carbonation2 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.Carbonation2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Carbonation2.setProperty("value", 0.2)
        self.Carbonation2.setObjectName("Carbonation2")
        self.verticalLayout_19.addWidget(self.Carbonation2)
        self.Calcination2 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.Calcination2.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Calcination2.setProperty("value", 0.6)
        self.Calcination2.setObjectName("Calcination2")
        self.verticalLayout_19.addWidget(self.Calcination2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_19)
        self.verticalLayout_9.addWidget(self.groupBox_8)
        self.groupBox_7.raise_()
        self.groupBox_2.raise_()
        self.groupBox_6.raise_()
        self.groupBox_8.raise_()
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки"))
        self.groupBox.setTitle(_translate("Settings", "Влажность, %"))
        self.label_2.setText(_translate("Settings", "Влажность шихты, поступающей на спекание"))
        self.label_7.setText(_translate("Settings", "Влажность белого шлама"))
        self.label_11.setText(_translate("Settings", "Влажность гидроксида алюминия"))
        self.label_10.setText(_translate("Settings", "Влажность отвального шлама"))
        self.groupBox_4.setTitle(_translate("Settings", "Расход воды на промывку"))
        self.label_14.setText(_translate("Settings", "<html><head/><body><p>Отвального шлама, м<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.label_17.setText(_translate("Settings", "<html><head/><body><p>Белого шлама, м<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.label_15.setText(_translate("Settings", "<html><head/><body><p>Карбонатного шлама, м<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.label_16.setText(_translate("Settings", "<html><head/><body><p>Гидроксида алюминия, м<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.groupBox_9.setTitle(_translate("Settings", "Прочее"))
        self.label_50.setText(_translate("Settings", "Товарный выход глинозема, %"))
        self.label_51.setText(_translate("Settings", "<html><head/><body><p>Извлечение Al₂O₃ при выщелачивании спека, %</p></body></html>"))
        self.label_52.setText(_translate("Settings", "Масса исходного глинозема, кг"))
        self.label_8.setText(_translate("Settings", "Кремневый модуль алюминатного раствора до обескремневания"))
        self.label_53.setText(_translate("Settings", "Кремневый модуль алюминатного раствора после первой стадии обескремневания"))
        self.label_9.setText(_translate("Settings", "Каустический модуль модуль алюминатного раствора после второй стадии обескремнивания"))
        self.label_54.setText(_translate("Settings", "Общий модуль алюминатного раствора после второй стадии обескремнивания"))
        self.label_55.setText(_translate("Settings", "Каустичиский модуль алюминатного раствора после регенерации КГГ"))
        self.label_12.setText(_translate("Settings", "Каустический модуль маточного раствора после карбонизации"))
        self.groupBox_5.setTitle(_translate("Settings", "Потери Al₂O₃ и Na₂O по переделам производства, %"))
        self.label_18.setText(_translate("Settings", "<html><head/><body><p>Дробление</p></body></html>"))
        self.label_21.setText(_translate("Settings", "<html><head/><body><p>Размол</p></body></html>"))
        self.label_19.setText(_translate("Settings", "<html><head/><body><p>Спекание</p></body></html>"))
        self.label_13.setText(_translate("Settings", "Дробление спека"))
        self.label_22.setText(_translate("Settings", "<html><head/><body><p>Выщелачивание спека, химические потери</p></body></html>"))
        self.label_23.setText(_translate("Settings", "<html><head/><body><p>Выщелачивание спека, недоотмывка</p></body></html>"))
        self.label_24.setText(_translate("Settings", "<html><head/><body><p>Обескремнивание</p></body></html>"))
        self.label_25.setText(_translate("Settings", "<html><head/><body><p>Карбонизация</p></body></html>"))
        self.label_27.setText(_translate("Settings", "<html><head/><body><p>Кальцинация</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Settings", "Первая шихта"))
        self.groupBox_2.setTitle(_translate("Settings", "Влажность, %"))
        self.label_3.setText(_translate("Settings", "Влажность шихты, поступающей на спекание"))
        self.label_20.setText(_translate("Settings", "Влажность белого шлама"))
        self.label_28.setText(_translate("Settings", "Влажность гидроксида алюминия"))
        self.label_29.setText(_translate("Settings", "Влажность отвального шлама"))
        self.groupBox_6.setTitle(_translate("Settings", "Расход воды на промывку"))
        self.label_30.setText(_translate("Settings", "<html><head/><body><p>Отвального шлама, м<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.label_31.setText(_translate("Settings", "<html><head/><body><p>Белого шлама, м<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.label_32.setText(_translate("Settings", "<html><head/><body><p>Карбонатного шлама, м<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.label_33.setText(_translate("Settings", "<html><head/><body><p>Гидроксида алюминия, м<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.groupBox_7.setTitle(_translate("Settings", "Прочее"))
        self.label_34.setText(_translate("Settings", "Товарный выход глинозема, %"))
        self.label_35.setText(_translate("Settings", "<html><head/><body><p>Извлечение Al₂O₃ при выщелачивании спека, %</p></body></html>"))
        self.label_36.setText(_translate("Settings", "Масса исходного глинозема, кг"))
        self.label_6.setText(_translate("Settings", "Кремневый модуль алюминатного раствора до обескремневания"))
        self.label_47.setText(_translate("Settings", "Кремневый модуль алюминатного раствора после первой стадии обескремневания"))
        self.label_4.setText(_translate("Settings", "Каустический модуль модуль алюминатного раствора после второй стадии обескремнивания"))
        self.label_48.setText(_translate("Settings", "Общий модуль алюминатного раствора после второй стадии обескремнивания"))
        self.label_49.setText(_translate("Settings", "Каустичиский модуль алюминатного раствора после регенерации КГГ"))
        self.label_5.setText(_translate("Settings", "Каустический модуль маточного раствора после карбонизации"))
        self.groupBox_8.setTitle(_translate("Settings", "Потери Al₂O₃ и Na₂O по переделам производства, %"))
        self.label_37.setText(_translate("Settings", "<html><head/><body><p>Дробление</p></body></html>"))
        self.label_38.setText(_translate("Settings", "<html><head/><body><p>Размол</p></body></html>"))
        self.label_39.setText(_translate("Settings", "<html><head/><body><p>Спекание</p></body></html>"))
        self.label_40.setText(_translate("Settings", "Дробление спека"))
        self.label_41.setText(_translate("Settings", "<html><head/><body><p>Выщелачивание спека, химические потери</p></body></html>"))
        self.label_42.setText(_translate("Settings", "<html><head/><body><p>Выщелачивание спека, недоотмывка</p></body></html>"))
        self.label_43.setText(_translate("Settings", "<html><head/><body><p>Обескремнивание</p></body></html>"))
        self.label_44.setText(_translate("Settings", "<html><head/><body><p>Карбонизация</p></body></html>"))
        self.label_46.setText(_translate("Settings", "<html><head/><body><p>Кальцинация</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "Вторая шихта"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())

