# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingMean.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BauxtifierMean(object):
    def setupUi(self, Bauxtifier):
        Bauxtifier.setObjectName("Bauxtifier")
        Bauxtifier.setWindowModality(QtCore.Qt.ApplicationModal)
        Bauxtifier.resize(476, 743)
        Bauxtifier.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Bauxtifier.setAcceptDrops(False)
        Bauxtifier.setAnimated(True)
        Bauxtifier.setTabShape(QtWidgets.QTabWidget.Triangular)
        Bauxtifier.setDockNestingEnabled(False)
        Bauxtifier.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Bauxtifier)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.percentage = QtWidgets.QLabel(self.groupBox)
        self.percentage.setObjectName("percentage")
        self.horizontalLayout_2.addWidget(self.percentage)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMaximum(100)
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_17 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.cao_in_bauxite1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.cao_in_bauxite1.setObjectName("cao_in_bauxite1")
        self.gridLayout_15.addWidget(self.cao_in_bauxite1, 4, 1, 1, 1)
        self.co2_in_bauxite1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.co2_in_bauxite1.setObjectName("co2_in_bauxite1")
        self.gridLayout_15.addWidget(self.co2_in_bauxite1, 5, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.groupBox_17)
        self.label_70.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_15.addWidget(self.label_70, 7, 0, 1, 1)
        self.moisture_in_bauxite1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.moisture_in_bauxite1.setObjectName("moisture_in_bauxite1")
        self.gridLayout_15.addWidget(self.moisture_in_bauxite1, 8, 1, 1, 1)
        self.sio2_in_bauxite1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.sio2_in_bauxite1.setObjectName("sio2_in_bauxite1")
        self.gridLayout_15.addWidget(self.sio2_in_bauxite1, 2, 1, 1, 1)
        self.tio2_in_bauxite1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.tio2_in_bauxite1.setObjectName("tio2_in_bauxite1")
        self.gridLayout_15.addWidget(self.tio2_in_bauxite1, 3, 1, 1, 1)
        self.al2o3_in_bauxite1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.al2o3_in_bauxite1.setObjectName("al2o3_in_bauxite1")
        self.gridLayout_15.addWidget(self.al2o3_in_bauxite1, 0, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.groupBox_17)
        self.label_71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout_15.addWidget(self.label_71, 8, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox_17)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_15.addWidget(self.label_72, 6, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.groupBox_17)
        self.label_73.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_15.addWidget(self.label_73, 0, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.groupBox_17)
        self.label_74.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_74.setObjectName("label_74")
        self.gridLayout_15.addWidget(self.label_74, 4, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_17)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_15.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.groupBox_17)
        self.label_83.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_15.addWidget(self.label_83, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem1, 4, 2, 1, 1)
        self.trace_elements_in_bauxite1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.trace_elements_in_bauxite1.setObjectName("trace_elements_in_bauxite1")
        self.gridLayout_15.addWidget(self.trace_elements_in_bauxite1, 7, 1, 1, 1)
        self.fe2o3_in_bauxite1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.fe2o3_in_bauxite1.setObjectName("fe2o3_in_bauxite1")
        self.gridLayout_15.addWidget(self.fe2o3_in_bauxite1, 1, 1, 1, 1)
        self.other_elements_in_bauxite1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.other_elements_in_bauxite1.setObjectName("other_elements_in_bauxite1")
        self.gridLayout_15.addWidget(self.other_elements_in_bauxite1, 6, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.groupBox_17)
        self.label_84.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_15.addWidget(self.label_84, 1, 0, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.groupBox_17)
        self.label_85.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_85.setObjectName("label_85")
        self.gridLayout_15.addWidget(self.label_85, 3, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_17)
        self.groupBox_18 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_91 = QtWidgets.QLabel(self.groupBox_18)
        self.label_91.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_91.setObjectName("label_91")
        self.gridLayout_16.addWidget(self.label_91, 7, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem2, 9, 1, 1, 1)
        self.tio2_in_bauxite2 = QtWidgets.QLineEdit(self.groupBox_18)
        self.tio2_in_bauxite2.setObjectName("tio2_in_bauxite2")
        self.gridLayout_16.addWidget(self.tio2_in_bauxite2, 3, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.groupBox_18)
        self.label_92.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_92.setObjectName("label_92")
        self.gridLayout_16.addWidget(self.label_92, 6, 0, 1, 1)
        self.co2_in_bauxite2 = QtWidgets.QLineEdit(self.groupBox_18)
        self.co2_in_bauxite2.setObjectName("co2_in_bauxite2")
        self.gridLayout_16.addWidget(self.co2_in_bauxite2, 5, 1, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.groupBox_18)
        self.label_93.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_93.setObjectName("label_93")
        self.gridLayout_16.addWidget(self.label_93, 4, 0, 1, 1)
        self.moisture_in_bauxite2 = QtWidgets.QLineEdit(self.groupBox_18)
        self.moisture_in_bauxite2.setObjectName("moisture_in_bauxite2")
        self.gridLayout_16.addWidget(self.moisture_in_bauxite2, 8, 1, 1, 1)
        self.other_elements_in_bauxite2 = QtWidgets.QLineEdit(self.groupBox_18)
        self.other_elements_in_bauxite2.setObjectName("other_elements_in_bauxite2")
        self.gridLayout_16.addWidget(self.other_elements_in_bauxite2, 6, 1, 1, 1)
        self.fe2o3_in_bauxite2 = QtWidgets.QLineEdit(self.groupBox_18)
        self.fe2o3_in_bauxite2.setObjectName("fe2o3_in_bauxite2")
        self.gridLayout_16.addWidget(self.fe2o3_in_bauxite2, 1, 1, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.groupBox_18)
        self.label_94.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_94.setObjectName("label_94")
        self.gridLayout_16.addWidget(self.label_94, 1, 0, 1, 1)
        self.trace_elements_in_bauxite2 = QtWidgets.QLineEdit(self.groupBox_18)
        self.trace_elements_in_bauxite2.setObjectName("trace_elements_in_bauxite2")
        self.gridLayout_16.addWidget(self.trace_elements_in_bauxite2, 7, 1, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.groupBox_18)
        self.label_95.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_95.setObjectName("label_95")
        self.gridLayout_16.addWidget(self.label_95, 8, 0, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.groupBox_18)
        self.label_96.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_96.setObjectName("label_96")
        self.gridLayout_16.addWidget(self.label_96, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem3, 4, 2, 1, 1)
        self.cao_in_bauxite2 = QtWidgets.QLineEdit(self.groupBox_18)
        self.cao_in_bauxite2.setObjectName("cao_in_bauxite2")
        self.gridLayout_16.addWidget(self.cao_in_bauxite2, 4, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_18)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_16.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.groupBox_18)
        self.label_97.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_97.setObjectName("label_97")
        self.gridLayout_16.addWidget(self.label_97, 5, 0, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.groupBox_18)
        self.label_98.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_98.setObjectName("label_98")
        self.gridLayout_16.addWidget(self.label_98, 3, 0, 1, 1)
        self.al2o3_in_bauxite2 = QtWidgets.QLineEdit(self.groupBox_18)
        self.al2o3_in_bauxite2.setObjectName("al2o3_in_bauxite2")
        self.gridLayout_16.addWidget(self.al2o3_in_bauxite2, 0, 1, 1, 1)
        self.sio2_in_bauxite2 = QtWidgets.QLineEdit(self.groupBox_18)
        self.sio2_in_bauxite2.setObjectName("sio2_in_bauxite2")
        self.gridLayout_16.addWidget(self.sio2_in_bauxite2, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_18)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem5 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 8, 2, 1, 1)
        self.co2_in_white_sludge1 = QtWidgets.QLineEdit(self.groupBox_13)
        self.co2_in_white_sludge1.setObjectName("co2_in_white_sludge1")
        self.gridLayout_11.addWidget(self.co2_in_white_sludge1, 9, 1, 1, 1)
        self.na2o_in_white_sludge1 = QtWidgets.QLineEdit(self.groupBox_13)
        self.na2o_in_white_sludge1.setObjectName("na2o_in_white_sludge1")
        self.gridLayout_11.addWidget(self.na2o_in_white_sludge1, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_13)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 8, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_13)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 10, 0, 1, 1)
        self.sio2_in_white_sludge1 = QtWidgets.QLineEdit(self.groupBox_13)
        self.sio2_in_white_sludge1.setObjectName("sio2_in_white_sludge1")
        self.gridLayout_11.addWidget(self.sio2_in_white_sludge1, 6, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_13)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 9, 0, 1, 1)
        self.trace_elements_in_white_sludge1 = QtWidgets.QLineEdit(self.groupBox_13)
        self.trace_elements_in_white_sludge1.setObjectName("trace_elements_in_white_sludge1")
        self.gridLayout_11.addWidget(self.trace_elements_in_white_sludge1, 10, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_13)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_11.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_13)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_11.addWidget(self.label_31, 6, 0, 1, 1)
        self.al2o3_in_white_sludge1 = QtWidgets.QLineEdit(self.groupBox_13)
        self.al2o3_in_white_sludge1.setObjectName("al2o3_in_white_sludge1")
        self.gridLayout_11.addWidget(self.al2o3_in_white_sludge1, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem6, 12, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_13)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.groupBox_13)
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_11.addWidget(self.label_62, 0, 0, 1, 1)
        self.fe2o3_in_white_sludge1 = QtWidgets.QLineEdit(self.groupBox_13)
        self.fe2o3_in_white_sludge1.setObjectName("fe2o3_in_white_sludge1")
        self.gridLayout_11.addWidget(self.fe2o3_in_white_sludge1, 5, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_13)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_11.addWidget(self.label_33, 5, 0, 1, 1)
        self.cao_in_white_sludge1 = QtWidgets.QLineEdit(self.groupBox_13)
        self.cao_in_white_sludge1.setObjectName("cao_in_white_sludge1")
        self.gridLayout_11.addWidget(self.cao_in_white_sludge1, 8, 1, 1, 1)
        self.white_sludge_mass1 = QtWidgets.QLineEdit(self.groupBox_13)
        self.white_sludge_mass1.setObjectName("white_sludge_mass1")
        self.gridLayout_11.addWidget(self.white_sludge_mass1, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.limestone_sio21 = QtWidgets.QLineEdit(self.groupBox_14)
        self.limestone_sio21.setObjectName("limestone_sio21")
        self.gridLayout_12.addWidget(self.limestone_sio21, 3, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.groupBox_14)
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_12.addWidget(self.label_63, 6, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.groupBox_14)
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_12.addWidget(self.label_64, 5, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.groupBox_14)
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName("label_65")
        self.gridLayout_12.addWidget(self.label_65, 1, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.groupBox_14)
        self.label_66.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_12.addWidget(self.label_66, 3, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem7, 7, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_14)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_12.addWidget(self.label_34, 2, 0, 1, 1)
        self.limestone_co21 = QtWidgets.QLineEdit(self.groupBox_14)
        self.limestone_co21.setObjectName("limestone_co21")
        self.gridLayout_12.addWidget(self.limestone_co21, 2, 1, 1, 1)
        self.limestone_other_elements1 = QtWidgets.QLineEdit(self.groupBox_14)
        self.limestone_other_elements1.setObjectName("limestone_other_elements1")
        self.gridLayout_12.addWidget(self.limestone_other_elements1, 5, 1, 1, 1)
        self.limestone_moisture1 = QtWidgets.QLineEdit(self.groupBox_14)
        self.limestone_moisture1.setObjectName("limestone_moisture1")
        self.gridLayout_12.addWidget(self.limestone_moisture1, 6, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem8, 1, 2, 1, 1)
        self.limestone_cao1 = QtWidgets.QLineEdit(self.groupBox_14)
        self.limestone_cao1.setObjectName("limestone_cao1")
        self.gridLayout_12.addWidget(self.limestone_cao1, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_14)
        self.groupBox_16 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.soda_mass1 = QtWidgets.QLineEdit(self.groupBox_16)
        self.soda_mass1.setObjectName("soda_mass1")
        self.gridLayout_13.addWidget(self.soda_mass1, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem9, 2, 2, 1, 1)
        self.na2co3_in_soda1 = QtWidgets.QLineEdit(self.groupBox_16)
        self.na2co3_in_soda1.setObjectName("na2co3_in_soda1")
        self.gridLayout_13.addWidget(self.na2co3_in_soda1, 1, 1, 1, 1)
        self.soda_moisture1 = QtWidgets.QLineEdit(self.groupBox_16)
        self.soda_moisture1.setObjectName("soda_moisture1")
        self.gridLayout_13.addWidget(self.soda_moisture1, 4, 1, 1, 1)
        self.soda_other_elements1 = QtWidgets.QLineEdit(self.groupBox_16)
        self.soda_other_elements1.setObjectName("soda_other_elements1")
        self.gridLayout_13.addWidget(self.soda_other_elements1, 2, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.groupBox_16)
        self.label_67.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_67.setObjectName("label_67")
        self.gridLayout_13.addWidget(self.label_67, 4, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.groupBox_16)
        self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_13.addWidget(self.label_68, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem10, 5, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.groupBox_16)
        self.label_69.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_13.addWidget(self.label_69, 0, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_16)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_13.addWidget(self.label_35, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_16)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.settingButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingButton.setObjectName("settingButton")
        self.horizontalLayout_5.addWidget(self.settingButton)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_5.addWidget(self.runButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        Bauxtifier.setCentralWidget(self.centralwidget)

        self.retranslateUi(Bauxtifier)
        self.horizontalSlider.valueChanged['int'].connect(self.percentage.setNum)
        self.horizontalSlider.valueChanged['int'].connect(self.label_5_setNum)
        QtCore.QMetaObject.connectSlotsByName(Bauxtifier)
    
    def label_5_setNum(self, value):
        _translate = QtCore.QCoreApplication.translate
        self.label_5.setText(_translate("Bauxtifier", str(100-value)))
    
    def retranslateUi(self, Bauxtifier):
        _translate = QtCore.QCoreApplication.translate
        Bauxtifier.setWindowTitle(_translate("Bauxtifier", "Bauxtifier"))
        self.label.setText(_translate("Bauxtifier", "Введите исходные данные"))
        self.groupBox.setTitle(_translate("Bauxtifier", "Соотношение бокситов"))
        self.label_2.setText(_translate("Bauxtifier", "(Первый боксит)% : (Второй боксит)%  ="))
        self.percentage.setText(_translate("Bauxtifier", "0"))
        self.label_4.setText(_translate("Bauxtifier", ":"))
        self.label_5.setText(_translate("Bauxtifier", "100"))
        self.groupBox_17.setTitle(_translate("Bauxtifier", "Состав первого боксита"))
        self.cao_in_bauxite1.setText(_translate("Bauxtifier", "2.8"))
        self.co2_in_bauxite1.setText(_translate("Bauxtifier", "2.2"))
        self.label_70.setText(_translate("Bauxtifier", "П.п.п, %"))
        self.moisture_in_bauxite1.setText(_translate("Bauxtifier", "7.0"))
        self.sio2_in_bauxite1.setText(_translate("Bauxtifier", "8.14"))
        self.tio2_in_bauxite1.setText(_translate("Bauxtifier", "2.6"))
        self.al2o3_in_bauxite1.setText(_translate("Bauxtifier", "48.0"))
        self.label_71.setText(_translate("Bauxtifier", "Влага, %"))
        self.label_72.setText(_translate("Bauxtifier", "Прочие, %"))
        self.label_73.setText(_translate("Bauxtifier", "<html><head/><body><p>Al<span style=\" vertical-align:sub;\">2</span>O<span style=\" vertical-align:sub;\">3</span>, %</p></body></html>"))
        self.label_74.setText(_translate("Bauxtifier", "<html><head/><body><p>CaO, %</p></body></html>"))
        self.label_38.setText(_translate("Bauxtifier", "<html><head/><body><p>SiO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.label_83.setText(_translate("Bauxtifier", "<html><head/><body><p>CO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.trace_elements_in_bauxite1.setText(_translate("Bauxtifier", "10.8"))
        self.fe2o3_in_bauxite1.setText(_translate("Bauxtifier", "24.0"))
        self.other_elements_in_bauxite1.setText(_translate("Bauxtifier", "1.46"))
        self.label_84.setText(_translate("Bauxtifier", "<html><head/><body><p>Fe<span style=\" vertical-align:sub;\">2</span>O<span style=\" vertical-align:sub;\">3</span>, %</p></body></html>"))
        self.label_85.setText(_translate("Bauxtifier", "<html><head/><body><p>TiO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.groupBox_18.setTitle(_translate("Bauxtifier", "Состав второго боксита"))
        self.label_91.setText(_translate("Bauxtifier", "П.п.п, %"))
        self.tio2_in_bauxite2.setText(_translate("Bauxtifier", "2.6"))
        self.label_92.setText(_translate("Bauxtifier", "Прочие, %"))
        self.co2_in_bauxite2.setText(_translate("Bauxtifier", "2.2"))
        self.label_93.setText(_translate("Bauxtifier", "<html><head/><body><p>CaO, %</p></body></html>"))
        self.moisture_in_bauxite2.setText(_translate("Bauxtifier", "7.0"))
        self.other_elements_in_bauxite2.setText(_translate("Bauxtifier", "1.46"))
        self.fe2o3_in_bauxite2.setText(_translate("Bauxtifier", "24.0"))
        self.label_94.setText(_translate("Bauxtifier", "<html><head/><body><p>Fe<span style=\" vertical-align:sub;\">2</span>O<span style=\" vertical-align:sub;\">3</span>, %</p></body></html>"))
        self.trace_elements_in_bauxite2.setText(_translate("Bauxtifier", "10.8"))
        self.label_95.setText(_translate("Bauxtifier", "Влага, %"))
        self.label_96.setText(_translate("Bauxtifier", "<html><head/><body><p>Al<span style=\" vertical-align:sub;\">2</span>O<span style=\" vertical-align:sub;\">3</span>, %</p></body></html>"))
        self.cao_in_bauxite2.setText(_translate("Bauxtifier", "2.8"))
        self.label_41.setText(_translate("Bauxtifier", "<html><head/><body><p>SiO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.label_97.setText(_translate("Bauxtifier", "<html><head/><body><p>CO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.label_98.setText(_translate("Bauxtifier", "<html><head/><body><p>TiO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.al2o3_in_bauxite2.setText(_translate("Bauxtifier", "48.0"))
        self.sio2_in_bauxite2.setText(_translate("Bauxtifier", "8.14"))
        self.groupBox_13.setTitle(_translate("Bauxtifier", "Состав белого шлама"))
        self.co2_in_white_sludge1.setText(_translate("Bauxtifier", "2.1"))
        self.na2o_in_white_sludge1.setText(_translate("Bauxtifier", "19.4"))
        self.label_16.setText(_translate("Bauxtifier", "<html><head/><body><p>CaO, %</p></body></html>"))
        self.label_21.setText(_translate("Bauxtifier", "П.п.п, %"))
        self.sio2_in_white_sludge1.setText(_translate("Bauxtifier", "29.4"))
        self.label_22.setText(_translate("Bauxtifier", "<html><head/><body><p>CO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.trace_elements_in_white_sludge1.setText(_translate("Bauxtifier", "11.8"))
        self.label_28.setText(_translate("Bauxtifier", "<html><head/><body><p>Al<span style=\" vertical-align:sub;\">2</span>O<span style=\" vertical-align:sub;\">3</span>, %</p></body></html>"))
        self.label_31.setText(_translate("Bauxtifier", "<html><head/><body><p>SiO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.al2o3_in_white_sludge1.setText(_translate("Bauxtifier", "31.3"))
        self.label_32.setText(_translate("Bauxtifier", "<html><head/><body><p>Na<span style=\" vertical-align:sub;\">2</span>O, %</p></body></html>"))
        self.label_62.setText(_translate("Bauxtifier", "Масса, кг"))
        self.fe2o3_in_white_sludge1.setText(_translate("Bauxtifier", "3.1"))
        self.label_33.setText(_translate("Bauxtifier", "<html><head/><body><p>Fe<span style=\" vertical-align:sub;\">2</span>O<span style=\" vertical-align:sub;\">3</span>, %</p></body></html>"))
        self.cao_in_white_sludge1.setText(_translate("Bauxtifier", "2.9"))
        self.white_sludge_mass1.setText(_translate("Bauxtifier", "120"))
        self.groupBox_14.setTitle(_translate("Bauxtifier", "Состав известняка"))
        self.limestone_sio21.setText(_translate("Bauxtifier", "1.3"))
        self.label_63.setText(_translate("Bauxtifier", "Влага, %"))
        self.label_64.setText(_translate("Bauxtifier", "Прочие, %"))
        self.label_65.setText(_translate("Bauxtifier", "<html><head/><body><p>CaO, %</p></body></html>"))
        self.label_66.setText(_translate("Bauxtifier", "<html><head/><body><p>SiO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.label_34.setText(_translate("Bauxtifier", "<html><head/><body><p>CO<span style=\" vertical-align:sub;\">2</span>, %</p></body></html>"))
        self.limestone_co21.setText(_translate("Bauxtifier", "42.6"))
        self.limestone_other_elements1.setText(_translate("Bauxtifier", "1.9"))
        self.limestone_moisture1.setText(_translate("Bauxtifier", "6.0"))
        self.limestone_cao1.setText(_translate("Bauxtifier", "54.2"))
        self.groupBox_16.setTitle(_translate("Bauxtifier", "Состав соды"))
        self.soda_mass1.setText(_translate("Bauxtifier", "150.00"))
        self.na2co3_in_soda1.setText(_translate("Bauxtifier", "98.6"))
        self.soda_moisture1.setText(_translate("Bauxtifier", "0.5"))
        self.soda_other_elements1.setText(_translate("Bauxtifier", "0.9"))
        self.label_67.setText(_translate("Bauxtifier", "Влага, %"))
        self.label_68.setText(_translate("Bauxtifier", "Прочие, %"))
        self.label_69.setText(_translate("Bauxtifier", "<html><head/><body><p>Масса, кг</p></body></html>"))
        self.label_35.setText(_translate("Bauxtifier", "<html><head/><body><p>Na<span style=\" vertical-align:sub;\">2</span>CO<span style=\" vertical-align:sub;\">3</span>, %</p></body></html>"))
        self.settingButton.setText(_translate("Bauxtifier", "Конфигурация"))
        self.runButton.setText(_translate("Bauxtifier", "Начать расчет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bauxtifier = QtWidgets.QMainWindow()
    ui = Ui_BauxtifierMean()
    ui.setupUi(Bauxtifier)
    Bauxtifier.show()
    sys.exit(app.exec_())

